##############################################
#               MY PLUGINS                   #
##############################################

plugins:
  lee:
    executor: central_deployment_agent
    source: https://github.com/lj020326/cloudify3-plugin-test/archive/master.zip
 